<?php
 
 $title = 'Produtos';
 $this->headTitle($title);
 ?>
 <h1><?= $this->escapeHtml($title); ?></h1>
 <p>
    <a href="<?= $this->url('produto', array('action'=>'add'));?>">Inserir novo produto</a>
 </p>

 <table class="table">
 <tr>
     <th>Nome</th>
     <th>Descrição</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($produtos as $produto) : ?>
 <tr>
     <td><?= $this->escapeHtml($produto->getNome());?></td>
     <td><?= $this->escapeHtml($produto->getDescricao());?></td>
     <td>
         <a class="btn btn-primary" href="<?= $this->url('produto',
             array('action'=>'edit', 'id' => $produto->getId()));?>">Editar</a>
         <a class="btn btn-danger" href="<?= $this->url('produto',
             array('action'=>'delete', 'id' => $produto->getId()));?>">Excluir</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>